import ChecklistPages from "@/app/components/ChecklistPage";
import Link from "next/link";

const categories = {
	Produce: [
		"Apples",
		"Bananas",
		"Oranges",
		"Avocados",
		"Lettuce",
		"Tomatoes",
		"Onions",
		"Garlic",
		"Potatoes",
		"Broccoli",
		"Carrots",
		"Mushrooms",
		"Lemons/Limes",
		"Herbs (cilantro, parsley, basil)",
	],
	"Dairy & Eggs": [
		"Milk",
		"Eggs",
		"Butter",
		"Yogurt",
		"Cheese (cheddar, mozzarella, parmesan)",
		"Cream cheese",
		"Sour cream",
	],
	"Meat & Seafood": [
		"Chicken breast/thighs",
		"Ground beef/turkey",
		"Beef (steak or roast)",
		"Pork chops",
		"Salmon or white fish",
		"Shrimp",
		"Bacon/sausage",
		"Deli meat (ham, turkey, roast beef)",
	],
	Pantry: [
		"Rice",
		"Pasta",
		"Bread",
		"Flour",
		"Sugar",
		"Salt",
		"Black pepper",
		"Olive oil",
		"Cooking oil",
		"Soy sauce",
		"Hot sauce",
		"Ketchup",
		"Mustard",
		"Mayonnaise",
		"Pasta sauce",
		"Canned beans (black, kidney, chickpeas)",
		"Canned tomatoes",
		"Broth (chicken or vegetable)",
		"Peanut butter",
		"Jam/jelly",
		"Honey",
		"Coffee/tea",
		"Cereal",
		"Oats",
	],
	Frozen: [
		"Frozen vegetables (peas, corn, mixed)",
		"Frozen fruit (berries, mango)",
		"Ice cream",
		"Frozen pizza",
		"Frozen meals",
		"Ice",
	],
	"Snacks & Drinks": [
		"Chips",
		"Crackers",
		"Nuts",
		"Popcorn",
		"Granola bars",
		"Cookies",
		"Juice",
		"Soda/sparkling water",
		"Sports drinks",
	],
	Household: [
		"Paper towels",
		"Toilet paper",
		"Tissues",
		"Trash bags",
		"Aluminum foil",
		"Plastic wrap",
		"Ziploc bags",
		"Dish soap",
		"Sponges",
		"Laundry detergent",
	],
};

export default function GroceriesPage() {
	return <ChecklistPages title="Grocery Shopping" categories={categories} />;
}
